spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/auth_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver



  data:
    redis:
      host: localhost
      port: 6379
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
    mongodb:
      uri: mongodb://root:root@localhost:27017/logdb?authSource=admin
      database: logdbfile