spring:
  grpc:
    client:
      channels:
        auth-service:
          address: static://localhost:9090
          negotiation-type: plaintext
        connection-management-service:
          address: static://localhost:9090
          negotiation-type: plaintext